# Generated by Django 6.1 on 2026-08-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('installation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vintage_category', models.CharField(default='MODERN', max_length=30)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['station', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('intervention_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('intervention_type', models.CharField(default='GENERAL', max_length=50)),
                ('applicable_station_type', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disruption_level', models.FloatField()),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interventions',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
            ],
            options={
                'db_table': 'plants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('line_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('line_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='core.plant')),
            ],
            options={
                'db_table': 'production_lines',
                'ordering': ['plant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('source_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(max_length=40)),
                ('connection_type', models.CharField(blank=True, max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.equipment')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.plant')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.productionline')),
            ],
            options={
                'db_table': 'data_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('prediction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('entity_type', models.CharField(max_length=20)),
                ('entity_id', models.CharField(max_length=100)),
                ('risk_type', models.CharField(max_length=50)),
                ('prediction_target', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('prediction_horizon_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'risk_predictions',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'timestamp'], name='risk_entity_time_idx'), models.Index(fields=['risk_type', 'timestamp'], name='risk_type_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionOutcome',
            fields=[
                ('outcome_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('outcome_type', models.CharField(max_length=50)),
                ('actual_outcome', models.CharField(max_length=100)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('matched', models.BooleanField(blank=True, null=True)),
                ('lead_time_minutes', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='core.riskprediction')),
            ],
            options={
                'db_table': 'prediction_outcomes',
            },
        ),
        migrations.CreateModel(
            name='PredictionExplanation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('contribution', models.FloatField()),
                ('direction', models.CharField(default='POSITIVE', max_length=20)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='core.riskprediction')),
            ],
            options={
                'db_table': 'prediction_explanations',
            },
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('root_cause_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'root_causes',
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_root_cause')],
            },
        ),
        migrations.CreateModel(
            name='PredictionRootCause',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contribution', models.FloatField()),
                ('confidence', models.FloatField()),
                ('evidence', models.TextField(blank=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='core.riskprediction')),
                ('root_cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_links', to='core.rootcause')),
            ],
            options={
                'db_table': 'prediction_root_causes',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=50)),
                ('measurement_type', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('sampling_rate', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='core.datasource')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.equipment')),
            ],
            options={
                'db_table': 'sensors',
                'ordering': ['equipment', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('simulation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('base_state_timestamp', models.DateTimeField()),
                ('scenario_name', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(default='WHAT_IF', max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('horizon_minutes', models.PositiveIntegerField()),
                ('number_of_runs', models.PositiveIntegerField()),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_runs', to='core.productionline')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_runs', to='core.plant')),
            ],
            options={
                'db_table': 'simulation_runs',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('decision_score', models.FloatField()),
                ('expected_throughput_gain', models.FloatField()),
                ('expected_risk_reduction', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.intervention')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.simulationrun')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('station_type', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('base_cycle_time', models.FloatField()),
                ('position', models.PositiveIntegerField()),
                ('instrumentation_status', models.CharField(default='PARTIAL', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.productionline')),
            ],
            options={
                'db_table': 'stations',
                'ordering': ['line', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.productionline')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.station')),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['line', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('maintenance_type', models.CharField(max_length=50)),
                ('failure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='core.datasource')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='core.equipment')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='core.station')),
            ],
            options={
                'db_table': 'maintenance_events',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.station'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.station'),
        ),
        migrations.CreateModel(
            name='StationDependency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(default='PROCESS', max_length=40)),
                ('propagation_weight', models.FloatField()),
                ('propagation_delay_minutes', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('downstream_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='core.station')),
                ('upstream_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='core.station')),
            ],
            options={
                'db_table': 'station_dependencies',
            },
        ),
        migrations.CreateModel(
            name='StationFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('avg_cycle_time', models.FloatField(blank=True, null=True)),
                ('cycle_time_std', models.FloatField(blank=True, null=True)),
                ('cycle_time_trend', models.FloatField(blank=True, null=True)),
                ('avg_torque', models.FloatField(blank=True, null=True)),
                ('torque_deviation', models.FloatField(blank=True, null=True)),
                ('temperature_mean', models.FloatField(blank=True, null=True)),
                ('vibration_mean', models.FloatField(blank=True, null=True)),
                ('alarm_rate', models.FloatField(default=0.0)),
                ('utilization', models.FloatField(default=0.0)),
                ('throughput', models.FloatField(default=0.0)),
                ('wip', models.FloatField(default=0.0)),
                ('blocking_time', models.FloatField(default=0.0)),
                ('starvation_time', models.FloatField(default=0.0)),
                ('sensor_coverage_ratio', models.FloatField(default=0.0)),
                ('data_completeness', models.FloatField(default=0.0)),
                ('imputation_ratio', models.FloatField(default=0.0)),
                ('manual_observation_count', models.PositiveIntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.station')),
            ],
            options={
                'db_table': 'station_features',
            },
        ),
        migrations.CreateModel(
            name='StationState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('health_state', models.CharField(max_length=30)),
                ('health_risk', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('wip', models.PositiveIntegerField(default=0)),
                ('utilization', models.FloatField(default=0.0)),
                ('throughput', models.FloatField(default=0.0)),
                ('blocking_time', models.FloatField(default=0.0)),
                ('starvation_time', models.FloatField(default=0.0)),
                ('current_cycle_time', models.FloatField(blank=True, null=True)),
                ('sensor_coverage', models.FloatField(default=0.0)),
                ('data_quality', models.FloatField(default=0.0)),
                ('instrumentation_status', models.CharField(default='PARTIAL', max_length=30)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.station')),
            ],
            options={
                'db_table': 'station_state',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=50)),
                ('production_order', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField(db_index=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.productionline')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('telemetry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cycle_time', models.FloatField(blank=True, null=True)),
                ('torque', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('vibration', models.FloatField(blank=True, null=True)),
                ('throughput', models.FloatField(blank=True, null=True)),
                ('machine_state', models.CharField(blank=True, max_length=30)),
                ('alarm_count', models.PositiveIntegerField(default=0)),
                ('data_quality', models.CharField(default='VALID', max_length=30)),
                ('is_imputed', models.BooleanField(default=False)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='core.datasource')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='core.equipment')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='core.sensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.station')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.vehicle')),
            ],
            options={
                'db_table': 'telemetry',
            },
        ),
        migrations.CreateModel(
            name='QualityEvent',
            fields=[
                ('quality_event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('defect_flag', models.BooleanField(default=False)),
                ('defect_type', models.CharField(blank=True, max_length=100, null=True)),
                ('defect_severity', models.CharField(blank=True, max_length=30, null=True)),
                ('rework_flag', models.BooleanField(default=False)),
                ('scrap_flag', models.BooleanField(default=False)),
                ('inspection_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('detection_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_quality_events', to='core.station')),
                ('origin_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_quality_events', to='core.station')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_events', to='core.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_events', to='core.vehicle')),
            ],
            options={
                'db_table': 'quality_events',
            },
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(max_length=30)),
                ('cycle_time', models.FloatField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_events', to='core.datasource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='core.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_events', to='core.vehicle')),
            ],
            options={
                'db_table': 'production_events',
            },
        ),
        migrations.CreateModel(
            name='ManualObservation',
            fields=[
                ('observation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('operator_reference', models.CharField(blank=True, max_length=100)),
                ('check_type', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_observations', to='core.datasource')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_observations', to='core.station')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_observations', to='core.vehicle')),
            ],
            options={
                'db_table': 'manual_observations',
            },
        ),
        migrations.CreateModel(
            name='VehicleExposure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('station_risk', models.FloatField()),
                ('exposure_weight', models.FloatField()),
                ('propagated_risk', models.FloatField()),
                ('exposure_start_time', models.DateTimeField(blank=True, null=True)),
                ('exposure_end_time', models.DateTimeField(blank=True, null=True)),
                ('source_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_exposures', to='core.riskprediction')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_exposures', to='core.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='core.vehicle')),
            ],
            options={
                'db_table': 'vehicle_exposure',
            },
        ),
        migrations.CreateModel(
            name='VehicleFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('variant', models.CharField(max_length=50)),
                ('avg_cycle_time', models.FloatField(blank=True, null=True)),
                ('cycle_time_deviation', models.FloatField(blank=True, null=True)),
                ('torque_deviation', models.FloatField(blank=True, null=True)),
                ('stations_exposed', models.PositiveIntegerField(default=0)),
                ('degraded_station_count', models.PositiveIntegerField(default=0)),
                ('cumulative_risk', models.FloatField(default=0.0)),
                ('quality_event_count', models.PositiveIntegerField(default=0)),
                ('manual_observation_count', models.PositiveIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.vehicle')),
            ],
            options={
                'db_table': 'vehicle_features',
            },
        ),
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=30)),
                ('quality_risk', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_source', models.CharField(blank=True, max_length=100)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle_states', to='core.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.vehicle')),
            ],
            options={
                'db_table': 'vehicle_state',
            },
        ),
        migrations.CreateModel(
            name='VehicleStationHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('entry_time', models.DateTimeField(db_index=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('cycle_time', models.FloatField(blank=True, null=True)),
                ('visit_type', models.CharField(default='NORMAL', max_length=30)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_history', to='core.station')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_history', to='core.vehicle')),
            ],
            options={
                'db_table': 'vehicle_station_history',
            },
        ),
        migrations.AddConstraint(
            model_name='productionline',
            constraint=models.UniqueConstraint(fields=('plant', 'name'), name='unique_line_name_per_plant'),
        ),
        migrations.AddIndex(
            model_name='predictionoutcome',
            index=models.Index(fields=['outcome_type', 'observed_at'], name='prediction_outcome_type_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionexplanation',
            index=models.Index(fields=['prediction', 'feature_name'], name='prediction_feature_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictionrootcause',
            constraint=models.UniqueConstraint(fields=('prediction', 'root_cause'), name='unique_prediction_root_cause'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['line', 'timestamp'], name='sim_line_time_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['plant', 'timestamp'], name='sim_plant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['timestamp', 'status'], name='recommendation_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('line', 'position'), name='unique_station_position_per_line'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('line', 'name'), name='unique_station_name_per_line'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('line', 'sequence_number'), name='unique_route_sequence_per_line'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('line', 'station'), name='unique_route_station_per_line'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['station', 'timestamp'], name='maintenance_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['equipment', 'timestamp'], name='maintenance_equipment_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='stationdependency',
            constraint=models.UniqueConstraint(fields=('upstream_station', 'downstream_station'), name='unique_station_dependency'),
        ),
        migrations.AddIndex(
            model_name='stationfeature',
            index=models.Index(fields=['station', 'timestamp'], name='station_feature_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stationstate',
            index=models.Index(fields=['station', 'timestamp'], name='station_state_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['station', 'timestamp'], name='telemetry_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['vehicle', 'timestamp'], name='telemetry_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['equipment', 'timestamp'], name='telemetry_equipment_time_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['data_source', 'timestamp'], name='telemetry_source_time_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['vehicle', 'timestamp'], name='quality_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['station', 'timestamp'], name='quality_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityevent',
            index=models.Index(fields=['defect_type', 'timestamp'], name='quality_defect_time_idx'),
        ),
        migrations.AddIndex(
            model_name='productionevent',
            index=models.Index(fields=['station', 'timestamp'], name='prod_event_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='productionevent',
            index=models.Index(fields=['vehicle', 'timestamp'], name='prod_event_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='manualobservation',
            index=models.Index(fields=['station', 'timestamp'], name='manual_obs_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='manualobservation',
            index=models.Index(fields=['vehicle', 'timestamp'], name='manual_obs_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexposure',
            index=models.Index(fields=['vehicle', 'timestamp'], name='exposure_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleexposure',
            index=models.Index(fields=['station', 'timestamp'], name='exposure_station_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclefeature',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicle_feature_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestate',
            index=models.Index(fields=['vehicle', 'timestamp'], name='vehicle_state_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestationhistory',
            index=models.Index(fields=['vehicle', 'entry_time'], name='vhist_vehicle_time_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclestationhistory',
            index=models.Index(fields=['station', 'entry_time'], name='vhist_station_time_idx'),
        ),
    ]
