# Generated by Django 6.1 on 2026-08-29 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionExecution',
            fields=[
                ('execution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('execution_notes', models.TextField(blank=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='core.recommendation')),
            ],
            options={
                'db_table': 'intervention_executions',
                'indexes': [models.Index(fields=['timestamp', 'status'], name='interv_exec_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimulationOutcome',
            fields=[
                ('outcome_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('simulated_throughput', models.FloatField()),
                ('simulated_risk', models.FloatField()),
                ('throughput_delta', models.FloatField()),
                ('risk_delta', models.FloatField()),
                ('is_bottleneck', models.BooleanField(default=False)),
                ('simulation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.simulationrun')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_outcomes', to='core.station')),
            ],
            options={
                'db_table': 'simulation_outcomes',
                'indexes': [models.Index(fields=['simulation_run', 'station'], name='sim_outcome_run_station_idx')],
            },
        ),
    ]
